# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property.
# include:
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
#     artifact-name: corne_central

include:
  - board: seeeduino_xiao_ble
    shield: LiNEA40_left rgbled_adapter

  - board: seeeduino_xiao_ble
    shield: LiNEA40_right rgbled_adapter
    # 警告でビルドを止めず、かつ DYA Studio の全機能を強制有効化する唯一の手段です
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_STUDIO_RPC_RUNTIME_INPUT_PROCESSOR=y
      -DCONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=y
      -DCONFIG_ZMK_STUDIO_RPC_SENSORS=y
      -DCONFIG_ZMK_SETTINGS_RPC_STUDIO_RPC=y
    snippet: studio-rpc-usb-uart
    extra-modules:
      - ../zmk-behavior-runtime-sensor-rotate
      - ../zmk-module-settings-rpc
      - ../zmk-module-ble-management
      - ../zmk-module-runtime-input-processor
      - ../zmk-pmw3610-driver
      - ../zmk-module-battery-history

  - board: seeeduino_xiao_ble
    shield: settings_reset
