# ZMK Studioの有効化
CONFIG_ZMK_STUDIO=y

# 🚨 USBスタックの有効化 (必須)
CONFIG_USB_DEVICE_STACK=y
# 🚨 CDC ACM クラスの有効化 (必須)
CONFIG_CDC_ACM_SERIAL=y 

# 🚨 ZMKがUSBで動作するために必要な追加設定
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_BOOT=y
