on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # ワークフロー全体（このジョブ全体）で使用する環境変数を定義する
    env:
      # エラーの原因であるZMK Studioスニペットの参照を無効化する
      ZMK_STUDIO_SNIPPET: ''
    
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2.1
